{% set name = "paradigm" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/paradigm-{{ version }}.tar.gz
  sha256: ffc058039895876faf8a6ceabea9780f506fe7bbeaef3bbaf754a5380f50f26d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - mypy >=0.812,<1.0
    - typing-extensions >=4.8.0,<5.0
    - memoir
    - reprit

test:
  imports:
    - paradigm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lycantropos/paradigm/
  summary: Python objects metadata parser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
