{% set name = "paradigm" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/paradigm-{{ version }}.tar.gz
  sha256: c8d18b549c8f8828db30d4961dfdef31b697e0d74aac998a1160126e0a94c583

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - typing_extensions >=4.14.1,<5.0
    - python >={{ python_min }}
    - mypy >=1.17.0,<2.0
    - typing-extensions >=4.8.0,<5.0
    - memoir
    - reprit

test:
  imports:
    - paradigm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lycantropos/paradigm/
  summary: Python objects metadata parser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
