{% set name = "paradigm" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/paradigm-{{ version }}.tar.gz
  sha256: 82f20034d67bbe4d3836986fb119b1d2163e25c653d5e2b1c3aeadc5492fc63f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - mypy <2.0,>=1.6.1
    - typing-extensions >=4.8.0,<5.0
    - memoir
    - reprit

test:
  imports:
    - paradigm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lycantropos/paradigm/
  summary: Python objects metadata parser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
